services:
  hut-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hut-webapp
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      BASE_URL: http://localhost:3000
    restart: unless-stopped
